# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:3.1.2

definitions:
  caches:
    bundler: ./vendor
    assets: tmp/cache/assets
  steps:
    - step: &build-and-test
        name: Unit tests
        caches:
          - bundler
          - assets
        script:
          - gem update --system
          - gem install bundler -v 2.2.7
          - bundle config set --local path 'vendor'
          - bundle install
          - bundle exec rake test

pipelines:
  pull-requests:
    '**':
      - step: *build-and-test
